language: julia

os:
  - linux

julia:
  - 1.6

# script:
#   - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("llmr"; coverage=true)'

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
