# .circleci/config.yml
# Source: https://discourse.julialang.org/t/continuous-integration-with-circle-ci/11642/8
version: 2.1
orbs:
  codecov: codecov/codecov@1.2.0 # Need to allow 3rd party orbs in project settings on circleci
jobs:
  build:
    working_directory: /root/project/blm # Clone into a directory whose name matches your Package.
    docker:
      - image: julia:1.6 # image comes from Docker hub
    steps:
      - checkout
      - run:
          name: Install and Test this package
          command: julia -e  'using Pkg; Pkg.activate("."); Pkg.test("blm", coverage=true);' # julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("blm"; coverage=true)' # julia -e  'using Pkg; Pkg.update(); Pkg.clone(pwd()); Pkg.build("blm"); Pkg.test("blm", coverage=true);'
      - run:
          name: Process code-coverage
          command: julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())' # julia -e 'using Pkg; cd(Pkg.dir("MyPkg")); Pkg.add("Coverage"); using Coverage; coverage = process_folder(); LCOV.writefile("coverage-lcov.info", coverage)'
      # - codecov/upload:
      #     file: "coverage-lcov.info"
      #     token: "..." # get from https://codecov.io/gh/github-name/MyPkg.jl/settings
